name: example
description: Example project on how to use liqpay
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility
  uuid: ^3.0.6
  intl: ^0.18.1

  # UI
  flutter_credit_card: ^3.0.6

  liqpay:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.olegnovosad.liqpay.example
    iosBundleIdentifier: com.olegnovosad.liqpay.example
